### ISSUE TITLE
Compare structs

### ISSUE THREAD

**Issue by djcarter85** [StephenCleary/Comparers#10]
Is there a way of automatically implementing the required comparison and equality operators for structs?

**Comment by StephenCleary** [comment]
Yes!

You cannot use the `ComparableBase<T>` or `ComparableBaseWithOperators<T>` with structs, since they cannot have base classes. However, you can use `ComparableImplementations`, as documented [here](https://github.com/StephenCleary/Comparers/wiki/Defining-Default-Comparers-for-a-Type).

I just checked in [some unit tests](https://github.com/StephenCleary/Comparers/blob/master/test/UnitTests/ComparableBase_Struct_DefaultComparer.cs) to show how this is done. This example has a struct that implements `IComparable<T>` / `IEquatable<T>` / `IComparable` (and overrides `Equals` and `GetHashCode`). If you want to go a step further and support operators, you can also write those operators out and forward them to `ComparableImplementations` following that same pattern.
